version: '3'
services:
  gpac:
    image: gpac_experiments:gpac
    container_name: gpac
    ports:
      - "1234:1234/udp"
    volumes:
      - ".:/tmp/workdir"
    command:
      - "sh"
      - "/tmp/workdir/scripts/run_gpac.sh"
    depends_on:
      - http_origin
    restart: always
  http_origin:
    image: nginx
    container_name: http_origin
    ports:
      - "8080:80"
    volumes:
      - ./scripts/:/etc/nginx/
      - ./logs/:/var/log/nginx/
      - ./content/:/var/www/html/live/upload
    command: [ nginx-debug, '-g', 'daemon off;' ]
  ffmpeg:
    image: gpac_experiments:ffmpeg
    container_name: ffmpeg
    volumes:
      - ".:/tmp/workdir"
    command:
      - "sh"
      - "/tmp/workdir/scripts/run_ffmpeg.sh"
    depends_on:
      - gpac
    restart: always

