version: '3'
services:
  ffmpeg:
    image: 391069704078.dkr.ecr.eu-central-1.amazonaws.com/video-distribution/ffmpeg:0.0.2
    container_name: ffmpeg-transcoder
    entrypoint: "ffmpeg"
    command: [ "-re", "-f", "lavfi", "-i", "testsrc=size=1280x720:rate=25", "-f", "lavfi", "-i", "sine=frequency=1000:duration=5", "-f", "mpegts", "-vcodec", "libx264", "-profile:v", "high444", "-b:v", "2000k", "-maxrate", "2000k", "-bufsize", "2000k", "-r:v", "25", "-g", "50", "udp://239.0.0.1:1234"  ]
  gpac-playlist:
    image: 391069704078.dkr.ecr.eu-central-1.amazonaws.com/video-distribution/gpac:0.0.3
    container_name: gpac-playlist
    links:
      - "ffmpeg"
    command: [ "sh", "-c", "gpac -i udp://239.0.0.1:1234 reframer:rt=on -o http://host.docker.internal:8080/live/upload/playlist.mpd:gpac:dual:buf=-100:segdur=2.0:cdur=0.2:asto=0.8:llhls=sf:hlsc=true:cmaf=cmfc:dmode=dynamic:profile=dashif.ll:utcs=https://time.akamai.com/?iso:hmode=push:template=segment_$$(openssl rand -hex 5):hmode=push" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
